### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by raavioli** [nikkatalnikov/bigkube#12]
@nikkatalnikov 
Can you suggest which java version are you running with this 

I am on
Mac OSx 10.14.6
SBT > 1.28 as suggested 
Java openjdk64-12.0.2

I tried sbt assembly , 

Loading project definition from ~/work/samples/bigkube/project(myinstall location)

no suitable image found.

**Comment by GrigorievNick** [comment]
Spark 2.x.x do not work with Java older then 1.8
